### ISSUE TITLE
Issue since Caali's update November 30th 2018

### ISSUE THREAD

**Issue by LeandraTS** [SerenTera/monster-marker#4]
Caali's Tera Proxy updated yesterday and since then there has been some issues with the Module.

Now it doesn't show special monsters like world boss helper module does.

Also the big beam of light that showed where boss spawned no longer shows either.

Here is the error I get.

`ERROR tera-proxy-game: [dispatch] write: failed to generate S_DESPAWN_DROPITEM<4>
error: [protocol] write - S_DESPAWN_DROPITEM<4>: error writing "gameId" (type: uint64)
data: { low: 798345, high: 0, unsigned: true }
reason: Cannot mix BigInt and other types, use explicit conversions
    at Writeable.uint64 (Y:\CaaliTeraProxy2\node_modules\tera-data-parser\lib\protocol\stream.js:129:24)
    at writeField (Y:\CaaliTeraProxy2\node_modules\tera-data-parser\lib\protocol\index.js:563:27)
    at TeraProtocol.write (Y:\CaaliTeraProxy2\node_modules\tera-data-parser\lib\protocol\index.js:578:7)
    at Dispatch.write (Y:\CaaliTeraProxy2\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:426:26)
    at Module.send (Y:\CaaliTeraProxy2\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:82:30)
    at despawnthis (Y:\CaaliTeraProxy2\bin\node_modules\monster-marker-master\index.js:178:7)`

Many thanks in advance for any help in fixing this issue when you have time to.

**Comment by SerenTera** [comment]
Ye, its to do with bigint updates. I'll fix this whenever my finals end, which is soonish x.x
